# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild_app', '0003_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='missingchild_app.Profile'),
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
