# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild_app', '0004_auto_20180118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(default='pic_folder/no-image.jpg', upload_to='pic_folder/'),
        ),
    ]
